# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginandregistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255)),
                ('users', models.ManyToManyField(related_name='wishes', to='Loginandregistration.User')),
            ],
        ),
    ]
