# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginandregistration', '0003_wish_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='created_by',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
