# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-22 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginandregistration', '0005_auto_20171122_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wish',
            name='created_by',
            field=models.CharField(default='none', max_length=255),
        ),
    ]
